services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: komoverse_assessment_laravel
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=komoverse_assessment
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

  db:
    image: mysql:8.0
    container_name: komoverse_assessment_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: komoverse_assessment
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: komoverse_assessment_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
